const words = [
  { word: "avicenna", meaning: "ابن سینا" },
  { word: "leopard", meaning: "پلنگ" },
  { word: "box", meaning: "جعبه" },
  { word: "laptop", meaning: "لپ‌تاپ" },
  { word: "visitor", meaning: "ملاقات‌کننده" },
  { word: "die out", meaning: "منقرض شدن" },
  { word: "cut", meaning: "قطع کردن (درخت، خط و ...)" },
  { word: "elephant", meaning: "فیل" },
  { word: "foot", meaning: "پا (از انگشت‌ها تا مچ)" },
  { word: "human", meaning: "انسان" },
  { word: "will", meaning: "[فعل کمکی زمان آینده]" },
  { word: "trip", meaning: "سفر" },
  { word: "earth", meaning: "زمین" },
  { word: "duck", meaning: "اردک" },
  { word: "travel", meaning: "سفر کردن" },
  { word: "life", meaning: "زندگی" },
  { word: "mean", meaning: "به معنی (چیزی) بودن" },
  { word: "endangered", meaning: "در معرض انقراض" },
  { word: "small", meaning: "کوچک" },
  { word: "gazelle", meaning: "غزال" },
  { word: "hurt", meaning: "زخمی کردن (فیزیکی)" },
  { word: "person", meaning: "فرد" },
  { word: "alive", meaning: "زنده" },
  { word: "plain", meaning: "جلگه" },
  { word: "tiger", meaning: "ببر" },
  { word: "instead", meaning: "در عوض" },
  { word: "sky", meaning: "آسمان" },
  { word: "information", meaning: "اطلاعات" },
  { word: "increase", meaning: "افزایش یافتن" },
  { word: "around", meaning: "دور" },
  { word: "future", meaning: "آینده" },
  { word: "wild", meaning: "وحشی" },
  { word: "dolphin", meaning: "دلفین" },
  { word: "injured", meaning: "آسیب‌دیده" },
  { word: "learn", meaning: "یاد گرفتن" },
  { word: "hear", meaning: "شنیدن" },
  { word: "hunter", meaning: "شکارچی" },
  { word: "today", meaning: "امروز" },
  { word: "pay attention!", meaning: "توجه کنید!" },
  { word: "destroy", meaning: "نابود کردن" },
  { word: "among", meaning: "(در) میان" },
  { word: "protect", meaning: "محافظت کردن" },
  { word: "hunt", meaning: "شکار کردن" },
  { word: "low", meaning: "کم" },
  { word: "save", meaning: "نجات دادن" },
  { word: "nowadays", meaning: "امروزه" },
  { word: "jungle", meaning: "جنگل" },
  { word: "for example", meaning: "برای مثال" },
  { word: "goat", meaning: "بز" },
  { word: "road", meaning: "جاده" },
  { word: "world", meaning: "جهان" },
  { word: "nature", meaning: "طبیعت" },
  { word: "high", meaning: "بلند" },
  { word: "beautiful", meaning: "زیبا" },
  { word: "zookeeper", meaning: "نگهبان باغ وحش" },
  { word: "natural", meaning: "طبیعی" },
  { word: "pain", meaning: "درد" },
  { word: "go hunting", meaning: "به شکار رفتن" },
  { word: "program", meaning: "برنامه (زمانی، کامپیوتری، تلویزیونی و ...)" },
  { word: "whale", meaning: "نهنگ" },
  { word: "forest", meaning: "جنگل" },
  { word: "bear", meaning: "خرس" },
  { word: "bird", meaning: "پرنده" },
  { word: "boring", meaning: "خسته‌کننده" },
  { word: "wildlife", meaning: "حیات وحش" },
  { word: "attention", meaning: "توجه" },
  { word: "recently", meaning: "اخیرا" },
  { word: "safe", meaning: "امن" },
  { word: "lose", meaning: "گم کردن" },
  { word: "go out", meaning: "بیرون رفتن" },
  { word: "giraffe", meaning: "زرافه" },
  { word: "anymore", meaning: "دیگر" },
  { word: "wolf", meaning: "گرگ" },
  { word: "cheetah", meaning: "یوزپلنگ" },
  { word: "danger", meaning: "خطر" },
  { word: "plant", meaning: "گیاه" },
  { word: "cat", meaning: "گربه" },
  { word: "noun", meaning: "اسم" },
  { word: "hopefully", meaning: "امیدوارم" },
  { word: "lion", meaning: "شیر (حیوان)" },
  { word: "zebra", meaning: "گورخر" },
  { word: "a few", meaning: "تعدادی" },
  { word: "movies", meaning: "سینما" },
  { word: "panda", meaning: "پاندا" },
  { word: "sea", meaning: "دریا" }
];