const words = [
  { word: "orbit", meaning: "مدار" },
  { word: "large", meaning: "بزرگ" },
  { word: "expensive", meaning: "گران" },
  { word: "telescope", meaning: "تلسکوپ" },
  { word: "long", meaning: "بلند" },
  { word: "quality", meaning: "ویژگی" },
  { word: "fact", meaning: "حقیقت" },
  { word: "daily", meaning: "روزانه" },
  { word: "microscope", meaning: "میکروسکوپ" },
  { word: "Neptune", meaning: "نپتون" },
  { word: "powerful", meaning: "نیرومند" },
  { word: "dark", meaning: "تیره" },
  { word: "farthest", meaning: "دورترین" },
  { word: "real", meaning: "واقعی" },
  { word: "opinion", meaning: "نظر" },
  { word: "thousand", meaning: "هزار" },
  { word: "easy", meaning: "ساده" },
  { word: "better", meaning: "بهتر" },
  { word: "Mars", meaning: "مریخ" },
  { word: "type", meaning: "نوع" },
  { word: "plasma", meaning: "پلاسما (خون)" },
  { word: "interested", meaning: "علاقه‌مند" },
  { word: "people", meaning: "مردم" },
  { word: "tall", meaning: "مرتفع" },
  { word: "best", meaning: "بهترین" },
  { word: "fatty", meaning: "چرب" },
  { word: "pepper", meaning: "فلفل" },
  { word: "much", meaning: "زیاد" },
  { word: "liquid", meaning: "نقد" },
  { word: "material", meaning: "ماده" },
  { word: "heavens", meaning: "آسمان ها" },
  { word: "camel", meaning: "شتر" },
  { word: "bad", meaning: "بد" },
  { word: "alike", meaning: "شبیه (به هم)" },
  { word: "gold", meaning: "طلا" },
  { word: "ugly", meaning: "زشت" },
  { word: "Saturn", meaning: "زحل (سیاره)" },
  { word: "cloudy", meaning: "ابری" },
  { word: "oxygen", meaning: "اکسیژن" },
  { word: "wooden", meaning: "چوبی" },
  { word: "more", meaning: "بیشتر" },
  { word: "exercise", meaning: "ورزش" },
  { word: "planet", meaning: "سیاره" },
  { word: "ticket", meaning: "بلیت" },
  { word: "worse", meaning: "بدتر" },
  { word: "medium", meaning: "متوسط" },
  { word: "golden", meaning: "طلایی (رنگ)" },
  { word: "different", meaning: "متفاوت" },
  { word: "carbon dioxide", meaning: "دی اکسید کربن (شیمی)" },
  { word: "without", meaning: "بدون" },
  { word: "silver", meaning: "نقره" },
  { word: "microbe", meaning: "میکروب" },
  { word: "wonder", meaning: "چیز عجیب" },
  { word: "sun", meaning: "خورشید" },
  { word: "rocky", meaning: "سنگی" },
  { word: "worst", meaning: "بدترین" },
  { word: "brain", meaning: "مغز" },
  { word: "above", meaning: "بالای" },
  { word: "most", meaning: "-ترین (نشانه صفت یا قید عالی)" },
  { word: "ring", meaning: "حلقه" },
  { word: "pump", meaning: "پمپاژ کردن" },
  { word: "strong", meaning: "نیرومند" },
  { word: "both", meaning: "هر دو" },
  { word: "creation", meaning: "آفرینش" },
  { word: "difficult", meaning: "مشکل" },
  { word: "Uranus", meaning: "اورانوس (سیاره)" },
  { word: "cross", meaning: "عبور کردن" },
  { word: "nation", meaning: "کشور" },
  { word: "metal", meaning: "فلز" },
  { word: "drop", meaning: "قطره" },
  { word: "ant", meaning: "مورچه" },
  { word: "far", meaning: "دور" },
  { word: "energy", meaning: "انرژی" },
  { word: "million", meaning: "میلیون" },
  { word: "heart", meaning: "قلب" },
  { word: "plastic", meaning: "پلاستیکی" },
  { word: "true", meaning: "واقعی" },
  { word: "as", meaning: "به اندازه" },
  { word: "useful", meaning: "سودمند" },
  { word: "body", meaning: "بدن" },
  { word: "round", meaning: "دور" },
  { word: "Mercury", meaning: "عطارد" },
  { word: "ball", meaning: "توپ" },
  { word: "blood", meaning: "خون" },
  { word: "fresh", meaning: "تازه" },
  { word: "go around", meaning: "حول چیزی گشتن" },
  { word: "paint", meaning: "رنگ" },
  { word: "seafood", meaning: "غذای دریایی" },
  { word: "organ", meaning: "عضو" },
  { word: "donate", meaning: "اهدا کردن" },
  { word: "moon", meaning: "ماه" },
  { word: "healthy", meaning: "سالم" },
  { word: "color", meaning: "رنگ" },
  { word: "everyone", meaning: "همه" },
  { word: "modern", meaning: "مدرن" },
  { word: "light", meaning: "روشن کردن" },
  { word: "delicious", meaning: "خوشمزه" },
  { word: "Venus", meaning: "زهره (سیاره)" },
  { word: "fast food", meaning: "فست فود" },
  { word: "defend", meaning: "دفاع کردن" },
  { word: "system", meaning: "سیستم" },
  { word: "carry", meaning: "حمل کردن" },
  { word: "farther", meaning: "دورتر" },
  { word: "adjective", meaning: "صفت" },
  { word: "cell", meaning: "سلول (زیست‌شناسی)" },
  { word: "observatory", meaning: "رصدخانه" },
  { word: "lamp", meaning: "چراغ" },
  { word: "clear", meaning: "واضح" },
  { word: "Jupiter", meaning: "مشتری (سیاره)" },
  { word: "collect", meaning: "جمع‌آوری کردن" },
  { word: "sign", meaning: "نشانه" },
  { word: "important", meaning: "مهم" },
  { word: "deep", meaning: "عمیق" },
  { word: "size", meaning: "اندازه" },
];
