const words = [
  { word: "sadly", meaning: "با ناراحتی" },
  { word: "love", meaning: "عاشق بودن" },
  { word: "researcher", meaning: "محقق" },
  { word: "prophet", meaning: "پیامبر" },
  { word: "skill", meaning: "مهارت" },
  { word: "express", meaning: "بیان کردن" },
  { word: "airplane", meaning: "هواپیما" },
  { word: "success", meaning: "موفقیت" },
  { word: "fortunately", meaning: "خوشبختانه" },
  { word: "yourselves", meaning: "[ضمیر انعکاسی دوم شخص جمع]" },
  { word: "action", meaning: "عمل" },
  { word: "smoking", meaning: "سیگار کشیدن" },
  { word: "translator", meaning: "مترجم" },
  { word: "scientist", meaning: "دانشمند" },
  { word: "verb", meaning: "فعل" },
  { word: "kitty", meaning: "گربه" },
  { word: "hearing", meaning: "شنوایی" },
  { word: "write", meaning: "نوشتن" },
  { word: "themselves", meaning: "[ضمیر انعکاسی سوم شخص جمع]" },
  { word: "antibiotic", meaning: "آنتی‌بیوتیک" },
  { word: "kill", meaning: "کشتن" },
  { word: "drink", meaning: "نوشیدن" },
  { word: "seek", meaning: "به‌دنبال گشتن" },
  { word: "invention", meaning: "اختراع" },
  { word: "laboratory", meaning: "آزمایشگاه" },
  { word: "invent", meaning: "اختراع کردن" },
  { word: "No pain no gain.", meaning: "نابرده رنج گنج میسر نمی شود." },
  { word: "short", meaning: "کوتاه" },
  { word: "cradle", meaning: "گهواره" },
  { word: "at first", meaning: "در ابتدا" },
  { word: "successful", meaning: "موفق" },
  { word: "poor", meaning: "فقیر" },
  { word: "PBUH", meaning: "صلی الله و علیه و آله" },
  { word: "state", meaning: "حالت" },
  { word: "same", meaning: "همان" },
  { word: "grave", meaning: "قبر" },
  { word: "penicillin", meaning: "پنی‌سیلین" },
  { word: "medicine", meaning: "دارو" },
  { word: "end", meaning: "پایان" },
  { word: "thinker", meaning: "اندیشمند" },
  { word: "emotion", meaning: "احساس" },
  { word: "uranium", meaning: "اورانیوم" },
  { word: "get around", meaning: "رفت‌و‌آمد کردن" },
  { word: "yourself", meaning: "[ضمیر انعکاسی دوم شخص]" },
  { word: "thought", meaning: "فکر" },
  { word: "solve", meaning: "حل کردن" },
  { word: "rain", meaning: "باران آمدن" },
  { word: "idea", meaning: "ایده" },
  { word: "herself", meaning: "[ضمیر انعکاسی سوم شخص مونث]" },
  { word: "outside", meaning: "بیرون" },
  { word: "easily", meaning: "به راحتی" },
  { word: "sense", meaning: "حس" },
  { word: "develop", meaning: "توسعه دادن" },
  { word: "hall", meaning: "سالن" },
  { word: "himself", meaning: "[ضمیر انعکاسی سوم شخص مذکر]" },
  { word: "emphasis", meaning: "تاکید" },
  { word: "rapidly", meaning: "سریعا" },
  { word: "fast", meaning: "سریع" },
  { word: "soon", meaning: "به زودی" },
  { word: "build", meaning: "ساختن" },
  { word: "belief", meaning: "باور" },
  { word: "camera", meaning: "دوربین" },
  { word: "strongly", meaning: "قویا" },
  { word: "suddenly", meaning: "ناگهان" },
  { word: "great", meaning: "بزرگ" },
  { word: "publish", meaning: "منتشر کردن" },
  { word: "itself", meaning: "[ضمیر انعکاسی سوم شخص خنثی]" },
  { word: "quit", meaning: "دست کشیدن" },
  { word: "weak", meaning: "سست" },
  { word: "light bulb", meaning: "لامپ" },
  { word: "writer", meaning: "نویسنده" },
  { word: "translate", meaning: "ترجمه کردن" },
  { word: "energetic", meaning: "پرانرژی" },
  { word: "such", meaning: "چنین" },
  { word: "holy", meaning: "مقدس" },
  { word: "noise", meaning: "صدا" },
  { word: "value", meaning: "ارزش" },
  { word: "ourselves", meaning: "[ضمیر انعکاسی اول شخص جمع]" },
  { word: "Believe me!", meaning: "باور کن!" },
  { word: "translation", meaning: "ترجمه" },
  { word: "grow up", meaning: "بزرگ شدن" },
  { word: "experiment", meaning: "آزمایش" },
  { word: "try", meaning: "سعی کردن" },
  { word: "yard", meaning: "حیاط" },
  { word: "story", meaning: "داستان" },
  { word: "believe in", meaning: "اعتقاد داشتن" },
  { word: "cool", meaning: "باشه!" },
  { word: "give up", meaning: "ترک کردن" },
  { word: "pass away", meaning: "فوت کردن" },
  { word: "hard", meaning: "سخت" },
  { word: "knowledge", meaning: "دانش" }
];
