const words = [
  { word: "may", meaning: "ممکن بودن" },
  { word: "Peru", meaning: "پرو" },
  { word: "four-season country", meaning: "کشور چهار فصل" },
  { word: "booklet", meaning: "کتابچه" },
  { word: "illness", meaning: "بیماری" },
  { word: "possibility", meaning: "امکان" },
  { word: "entertainment", meaning: "سرگرمی" },
  { word: "in", meaning: "در" },
  { word: "travel agent", meaning: "کارمند آژانس مسافرتی" },
  { word: "Chile", meaning: "شیلی" },
  { word: "May", meaning: "مه" },
  { word: "site", meaning: "مکان" },
  { word: "prepare", meaning: "آماده کردن" },
  { word: "host", meaning: "میزبان" },
  { word: "honestly", meaning: "صادقانه" },
  { word: "piano", meaning: "پیانو" },
  { word: "at", meaning: "در (زمان)" },
  { word: "rudely", meaning: "گستاخانه" },
  { word: "choice", meaning: "انتخاب" },
  { word: "vacation", meaning: "مرخصی" },
  { word: "image", meaning: "وجهه" },
  { word: "abroad", meaning: "خارج" },
  { word: "quickly", meaning: "سریع" },
  { word: "own", meaning: "خود" },
  { word: "probably", meaning: "احتمالاً" },
  { word: "ski", meaning: "اسکی کردن" },
  { word: "domestic", meaning: "(مربوط به) خانه" },
  { word: "most often", meaning: "اغلب" },
  { word: "adverb", meaning: "قید" },
  { word: "can", meaning: "توانستن" },
  { word: "hospitable", meaning: "مهمان‌نواز" },
  { word: "on", meaning: "در (زمان)" },
  { word: "spend", meaning: "صرف کردن" },
  { word: "flight", meaning: "پرواز" },
  { word: "attraction", meaning: "جذابیت" },
  { word: "vegetable", meaning: "سبزیجات" },
  { word: "should", meaning: "بایستن" },
  { word: "cannot", meaning: "can+not" },
  { word: "happily", meaning: "با خوشحالی" },
  { word: "possibly", meaning: "احتمالا" },
  { word: "sandwich", meaning: "ساندویچ" },
  { word: "culture", meaning: "فرهنگ" },
  { word: "carefully", meaning: "بادقت" },
  { word: "pyramid", meaning: "هرم" },
  { word: "destination", meaning: "مقصد" },
  { word: "suggestion", meaning: "پیشنهاد" },
  { word: "embassy", meaning: "سفارت" },
  { word: "remember", meaning: "به یاد آوردن" },
  { word: "desert touring", meaning: "کویر نوردی" },
  { word: "politely", meaning: "مودبانه" },
  { word: "historical", meaning: "تاریخی" },
  { word: "foreign", meaning: "خارجی" },
  { word: "comfortable", meaning: "راحت" },
  { word: "junk food", meaning: "غذای ناسالم" },
  { word: "behavior", meaning: "رفتار" },
  { word: "billion", meaning: "میلیارد" },
  { word: "Great Wall", meaning: "دیوار بزرگ چین" },
  { word: "morning", meaning: "صبح" },
  { word: "familiar", meaning: "آشنا" },
  { word: "afternoon", meaning: "بعدازظهر" },
  { word: "range", meaning: "گستره" },
  { word: "book", meaning: "رزرو کردن" },
  { word: "Italy", meaning: "ایتالیا" },
  { word: "ancient", meaning: "باستان" },
  { word: "holy shrine", meaning: "حرم مطهر" },
  { word: "traveler", meaning: "مسافر" },
  { word: "Beijing", meaning: "پکن (پایتخت چین)" },
  { word: "neatly", meaning: "مرتب" },
  { word: "actual", meaning: "واقعی" },
  { word: "home-made", meaning: "خانگی" },
  { word: "traditional", meaning: "سنتی" },
  { word: "inside", meaning: "داخل" },
  { word: "safely", meaning: "به سلامت" },
  { word: "India", meaning: "هندوستان" },
  { word: "loud", meaning: "بلند" },
  { word: "nicely", meaning: "به خوبی" },
  { word: "leave", meaning: "ترک کردن" },
  { word: "next to", meaning: "کنار" },
  { word: "paradise", meaning: "بهشت" },
  { word: "hard", meaning: "سخت" },
  { word: "bravely", meaning: "شجاعانه" },
  { word: "wind tower", meaning: "بادگیر (معماری)" },
  { word: "Egypt", meaning: "مصر (کشوری در قاره آفریقا)" },
  { word: "must", meaning: "باید" },
  { word: "late", meaning: "دیر" },
  { word: "in front of", meaning: "در مقابل" },
  { word: "popular", meaning: "پرطرفدار" },
  { word: "attract", meaning: "جذب کردن" },
  { word: "well", meaning: "به‌خوبی" },
  { word: "attractive", meaning: "جذاب" },
  { word: "patiently", meaning: "صبورانه" },
  { word: "rule", meaning: "قانون" },
  { word: "visa", meaning: "روادید" },
  { word: "chip", meaning: "چیپس (سیب‌زمینی)" },
  { word: "obligation", meaning: "وظیفه" },
  { word: "desert", meaning: "بیابان" },
  { word: "pilgrim", meaning: "زائر" },
  { word: "risk", meaning: "خطر" }
];
